services:
  postgres:
    image: postgres:16-alpine
    container_name: coop_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: coop_gig_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: coop_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@coop.local
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
